export const RetailerRoutes = {
  HOME: "Home",
  VIEW_DATA: "ViewData",
  UPLOAD_FILE: "uploadFile",
  OPTION: "Option",
  ORDER: "Order",
  PROFILE: "Profile",
  SCAN: "Scan",
  EDIT_PROFILE: "EditProfile",
  SETTING: "Setting",
  LOGIN: "Login",
  EMAIL_VERIFICATION: "EmailVerification",
  CREATE_NEW_ACCOUNT: "CreateNewAccount",
  RESET_PASSWORD: "resetPassword",
  SAVE_ORDER: "SaveOrder",
  PRODUCT_DESCRIPTION: "Product Description",
  SALES_GRAPH: "Sales Graph",
  TAB_CONTAINER: "tabContainer",
  PREVIEW_PDF: "Preview PDF",
  RENDER_PDF: "Render PDF",
  CART: "cart",
  FAILURE: "paymentFailed",
  SUCCESS: "paymentSuccess",
  SUBSCRIPTIONPLAN: "subscriptionPlan",
  LOADING: "LoadingScreen",
  OPTIONS: "Options",
  FAVOURITES: "Favourites",
  PRICEHISTORY: "PriceHistory",
  SEARCH: "Search",
} as const
